// Generated by gencpp from file assignment_1_intro_to_ros/WeatherInfoSrvRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_1_INTRO_TO_ROS_MESSAGE_WEATHERINFOSRVREQUEST_H
#define ASSIGNMENT_1_INTRO_TO_ROS_MESSAGE_WEATHERINFOSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_1_intro_to_ros
{
template <class ContainerAllocator>
struct WeatherInfoSrvRequest_
{
  typedef WeatherInfoSrvRequest_<ContainerAllocator> Type;

  WeatherInfoSrvRequest_()
    : zipCode(0)  {
    }
  WeatherInfoSrvRequest_(const ContainerAllocator& _alloc)
    : zipCode(0)  {
  (void)_alloc;
    }



   typedef int64_t _zipCode_type;
  _zipCode_type zipCode;




  typedef boost::shared_ptr< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherInfoSrvRequest_

typedef ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<std::allocator<void> > WeatherInfoSrvRequest;

typedef boost::shared_ptr< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest > WeatherInfoSrvRequestPtr;
typedef boost::shared_ptr< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest const> WeatherInfoSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment_1_intro_to_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'assignment_1_intro_to_ros': ['/home/rogergomes/Frosty-The-Snowman/Assignment_1/catkin_ws/src/assignment_1_intro_to_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "795bba22484f07e427314e281e166a54";
  }

  static const char* value(const ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x795bba22484f07e4ULL;
  static const uint64_t static_value2 = 0x27314e281e166a54ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_1_intro_to_ros/WeatherInfoSrvRequest";
  }

  static const char* value(const ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 zipCode\n\
";
  }

  static const char* value(const ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zipCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherInfoSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_1_intro_to_ros::WeatherInfoSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "zipCode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.zipCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_1_INTRO_TO_ROS_MESSAGE_WEATHERINFOSRVREQUEST_H
