// Generated by gencpp from file beginner_tutorials/weather_msgs.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_WEATHER_MSGS_H
#define BEGINNER_TUTORIALS_MESSAGE_WEATHER_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct weather_msgs_
{
  typedef weather_msgs_<ContainerAllocator> Type;

  weather_msgs_()
    : zip(0)
    , location()
    , temperature(0.0)  {
    }
  weather_msgs_(const ContainerAllocator& _alloc)
    : zip(0)
    , location(_alloc)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _zip_type;
  _zip_type zip;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_type;
  _location_type location;

   typedef float _temperature_type;
  _temperature_type temperature;




  typedef boost::shared_ptr< ::beginner_tutorials::weather_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::weather_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct weather_msgs_

typedef ::beginner_tutorials::weather_msgs_<std::allocator<void> > weather_msgs;

typedef boost::shared_ptr< ::beginner_tutorials::weather_msgs > weather_msgsPtr;
typedef boost::shared_ptr< ::beginner_tutorials::weather_msgs const> weather_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::weather_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/akhil/git_work/EE5900/Frosty-The-Snowman/amkurup/ROS_tutorials/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::weather_msgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::weather_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::weather_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61580aab72e2795d86388fba43a63ac3";
  }

  static const char* value(const ::beginner_tutorials::weather_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61580aab72e2795dULL;
  static const uint64_t static_value2 = 0x86388fba43a63ac3ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/weather_msgs";
  }

  static const char* value(const ::beginner_tutorials::weather_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 zip\n\
string location\n\
float32 temperature\n\
";
  }

  static const char* value(const ::beginner_tutorials::weather_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zip);
      stream.next(m.location);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct weather_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::weather_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::weather_msgs_<ContainerAllocator>& v)
  {
    s << indent << "zip: ";
    Printer<int64_t>::stream(s, indent + "  ", v.zip);
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_WEATHER_MSGS_H
